openapi: 3.0.1
info:
  title: API de Microservicio de Cuentas
  version: 1.0.0
  description: Microservicio para la gestión de cuentas bancarias y operaciones.

servers:
  - url: https://account-ms-production.up.railway.app
    description: Servidor de producción
  #- url: http://localhost:8081
  #  description: Servidor local para desarrollo


paths:
  /cuentas:
    get:
      summary: Obtener todas las cuentas
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cuenta'

    post:
      summary: Crear nueva cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
      responses:
        '201':
          description: Cuenta creada

  /cuentas/{id}:
    get:
      summary: Obtener cuenta por ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Detalles de la cuenta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
        '404':
          description: Cuenta no encontrada

    put:
      summary: Actualizar cuenta
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
      responses:
        '200':
          description: Cuenta actualizada
        '404':
          description: Cuenta no encontrada

    delete:
      summary: Eliminar cuenta
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Cuenta eliminada
        '404':
          description: Cuenta no encontrada

  /cuentas/depositar/{id}:
    put:
      summary: Realizar depósito
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
        - name: monto
          in: query
          schema:
            type: number
          required: true
      responses:
        '200':
          description: Depósito exitoso
        '400':
          description: Monto inválido
        '404':
          description: Cuenta no encontrada

  /cuentas/retirar/{id}:
    put:
      summary: Realizar retiro
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
        - name: monto
          in: query
          schema:
            type: number
          required: true
      responses:
        '200':
          description: Retiro exitoso
        '400':
          description: Monto inválido
        '404':
          description: Cuenta no encontrada

components:
  schemas:
    Cuenta:
      type: object
      properties:
        id:
          type: integer
        numeroCuenta:
          type: string
          description: "10-12 dígitos"
        saldo:
          type: number
        tipoCuenta:
          type: string
          enum:
            - AHORROS
            - CORRIENTE
        clienteId:
          type: integer
        estado:
          type: string
          enum:
            - ACTIVO
            - INACTIVO
            - CERRADO
